
[terminal.shell]
# args = ["tmux attach || tmux -u"]
program = "wsl"

[window]
title = "wsl"

[general]
working_directory = '\\wsl$\Debian\home\jmzagorski'
import = ['C:\Users\511113\AppData\Roaming\alacritty\alacritty.toml']

[terminal]
