[colors.bright]
black = "0xbcbcbc"
blue = "0xd75f00"
cyan = "0x005faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0x878787"
text = "0xeeeeee"

[colors.normal]
black = "0xeeeeee"
blue = "0x0087af"
cyan = "0x005f87"
green = "0x008700"
magenta = "0x878787"
red = "0xaf0000"
white = "0x444444"
yellow = "0x5f8700"

[colors.primary]
background = "0xeeeeee"
foreground = "0x878787"

[font]
size = 11.0

[font.bold]
family = "Consolas"
style = "Bold"

[font.bold_italic]
family = "Consolas"
style = "Bold Italic"

[font.italic]
family = "Consolas"
style = "Italic"

[font.normal]
family = "Consolas"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"
opacity = 0.95

[scrolling]
history = 0
